#!/usr/bin/env python3
"""Build examples/vscode/tabulate.ggsql from examples/tabulate/*.ggsql.

Concatenates every scenario into a single file using the extension's
cell delimiter (`-- %%`). Open the file in VS Code or Positron with the
ggsql extension installed and use the ▶ Run Cell code lens above each
cell to execute the scenarios one at a time."""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = REPO_ROOT / "examples" / "tabulate"
OUTPUT = Path(__file__).with_name("tabulate.ggsql")

HEADER = """-- TABULATE examples — VS Code / Positron
--
-- Every scenario from examples/tabulate/ packaged as a single
-- multi-cell ggsql file. The `-- %%` lines below are cell delimiters
-- recognised by the ggsql VS Code extension; each cell has its own
-- "▶ Run Cell" code lens above it.
--
-- Generated by examples/vscode/build_ggsql.py — do not hand-edit.
"""


def main() -> int:
    files = sorted(SOURCE_DIR.glob("*.ggsql"))
    if not files:
        print(f"no .ggsql files in {SOURCE_DIR}", file=sys.stderr)
        return 1

    parts: list[str] = [HEADER.rstrip()]
    for path in files:
        slug = path.stem
        body = path.read_text().rstrip()
        parts.append("")
        parts.append(f"-- %% {slug}")
        parts.append(body)

    OUTPUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUTPUT} ({len(files)} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
