#!/usr/bin/env python3
"""Build ggsql-vscode/examples/tabulate.ggsql from scenarios/NN_slug.ggsql.

Concatenates every scenario file under `scenarios/` into a single
multi-cell file at the folder root, using the extension's cell
delimiter (`-- %%`). Open the file in VS Code or Positron with the
ggsql extension installed and use the ▶ Run Cell code lens above each
cell to execute the scenarios one at a time.

Run from any working directory:
    python3 ggsql-vscode/examples/build_ggsql.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SCENARIOS_DIR = SCRIPT_DIR / "scenarios"
OUTPUT = SCRIPT_DIR / "tabulate.ggsql"
SCENARIO_RE = re.compile(r"^\d+_.+\.ggsql$")

HEADER = """-- TABULATE examples — VS Code / Positron
--
-- Every scenarios/NN_slug.ggsql file packaged as a single multi-cell
-- ggsql file. The `-- %%` lines below are cell delimiters recognised
-- by the ggsql VS Code extension; each cell has its own
-- "▶ Run Cell" code lens above it.
--
-- Generated by ggsql-vscode/examples/build_ggsql.py — do not hand-edit.
"""


def main() -> int:
    files = sorted(p for p in SCENARIOS_DIR.glob("*.ggsql") if SCENARIO_RE.match(p.name))
    if not files:
        print(f"no NN_*.ggsql scenario files in {SCENARIOS_DIR}", file=sys.stderr)
        return 1

    parts: list[str] = [HEADER.rstrip()]
    for path in files:
        slug = path.stem
        body = path.read_text().rstrip()
        parts.append("")
        parts.append(f"-- %% {slug}")
        parts.append(body)

    OUTPUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUTPUT} ({len(files)} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
